### ISSUE TITLE
Description is missing

### ISSUE THREAD

**Issue by FREDVUNI** [Famba-Abdulnassiir/codebenders-js-challenges#1]
Add short details of the repo under the About section

**Comment by Famba-Abdulnassiir** [comment]
![Screenshot from 2023-06-23 09-54-34](https://github.com/Famba-Abdulnassiir/codebenders-js-challenges/assets/57795345/0aaf6553-0aa3-4677-88f0-5142bca2ff1e)
Did not intialize it when i was creating the Repo but added it in the readme file.

**Comment by Famba-Abdulnassiir** [comment]
Please advice on how to add it on already created project that didnt tick it on creation.

**Comment by Famba-Abdulnassiir** [comment]
Done thanks for the help.
